UBUNTU: SAUCE: LIRC_PVR150: depends on VIDEO_IVTV
Bug: #341477

The LIRC module for PVR150 needs the IVTV driver to compile:

Setup is 12556 bytes (padded to 12800 bytes).
System is 2499 kB
CRC de75b643
Kernel: arch/x86/boot/bzImage is ready  (#12)
ERROR: "ivtv_reset_ir_gpio" [ubuntu/lirc/lirc_pvr150/lirc_pvr150.ko] undefined!
WARNING: modpost: Found 2 section mismatch(es).
To see full details build your kernel with:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
make[1]: *** [__modpost] Error 1

Signed-off-by: Andy Isaacson <adi@hexapodia.org>
Signed-off-by: Stefan Bader <stefan.bader@canonical.com>