UBUNTU: SAUCE: [FTBS] armel: replace omap_set_gpio_debounce with gpio_set_debounce
The following upstream commit removed omap_set_gpio_debounce methods in
favor of using the gpiolib instead.

  commit 8156fae26aec0285840ffa6faff6cae017abe81b
  Author: Felipe Balbi <felipe.balbi@nokia.com>
  Date:   Wed May 26 14:42:24 2010 -0700

    arm: omap: remove the unused omap_gpio_set_debounce methods

Failing to replace omap_set_gpio_debouce with gpiolib results in a FTBS
error:

arch/arm/mach-omap2/board-omap3stalker.c:545: undefined reference to
`omap_set_gpio_debounce'
arch/arm/mach-omap2/board-omap3stalker.c:546: undefined reference to
`omap_set_gpio_debounce_time'

Signed-off-by: Leann Ogasawara <leann.ogasawara@canonical.com>