ARM: 5882/1: ARM: Fix uncompress code compile for different defines of flush(void)
BugLink: http://bugs.launchpad.net/bugs/319240
    commit b53e9b5ebd5c6e718f54bcacd4e97b71533ca681 upstream

Because of the include of the decompress_inflate.c file from
boot/compress/misc.c, there are different flush() defines:

In file included from arch/arm/boot/compressed/misc.c:249:
arch/arm/boot/compressed/../../../../lib/decompress_inflate.c:138:29: error: macro "flush" passed 2 arguments, but takes just 0

Fix this by removing the define of flush() in misc.c for
CONFIG_DEBUG_ICEDCC as it's already defined in mach/uncompress.h,
and that is being included unconditionally.

Also use a static inline function instead of define
for mach-mxc and mach-gemini to avoid similar bug
for those platforms.

(bryan.wu@canonical.com: back ported it to 2.6.31 for fsl-imx51)

Signed-off-by: Tony Lindgren <tony@atomide.com>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>
Signed-off-by: Bryan Wu <bryan.wu@canonical.com>