UBUNTU: [Config] imx51: disable MTD_MXC_DATAFLASH
This driver is exposing some compiler errors:
ERROR: "__aeabi_uldivmod" undefined!

Disable it for now till be find out what is it required for.

Signed-off-by: Amit Kucheria <amit.kucheria@canonical.com>