gpu: drm: Fix compile error
Compiler output:
drivers/gpu/drm/drm_edid.c: In function drm_detect_hdmi_monitor:
drivers/gpu/drm/drm_edid.c:707: error: array subscript is above array
bounds

I suspect this is a gcc bug. The array is allocated with size
MAX_EDID_EXT_NUM + 1, so the highest valid offset into it should be
MAX_EDID_EXT_NUM. This is the highest that (i + 1) can be in this
context, so everything should be okay.

Signed-off-by: Jeff Ohlstein <johlstei@quicinc.com>
Signed-off-by: David Brown <davidb@quicinc.com>