Revert "staging: brcm80211: fix "ERROR: return is not a function, paren...""
This reverts commit 42c7020244475a2eba53bab02b86c4982610bb3f.

Signed-off-by: Andy Whitcroft <apw@canonical.com>