Fix userspace build of linux/fs.h
dpkg uses fiemap but didn't particularly need to include stdint.h so
far.  Since 367a51a33902 ("fs: Add FITRIM ioctl"), build of linux/fs.h
failed in dpkg with:
In file included from ../../src/filesdb.c:27:0:
/usr/include/linux/fs.h:37:2: error: expected specifier-qualifier-list before 'uint64_t'

Use exportable type __u64 to avoid the dependency on stdint.h.

b31d42a5af18 fixed only the kernel build by including linux/types.h, but
this also fixed "make headers_check", so don't revert it.

Signed-off-by: Loïc Minier <loic.minier@linaro.org>
Tested-by: Arnd Bergmann <arnd.bergmann@linaro.org>
Cc: Lukas Czerner <lczerner@redhat.com>
Cc: Dmitry Monakhov <dmonakhov@openvz.org>
Cc: Theodore Ts'o <tytso@mit.edu>
Signed-off-by: Andy Whitcroft <apw@canonical.com>